version: '3'

services:
  frontend:
    image: cellphaser/frontend
    container_name: cellphaser-frontend
    command: yarn serve --port 8081
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:8081
  
  backend:
    image: cellphaser/backend
    container_name: cellphaser-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:8000

