# Generated by Django 2.2.7 on 2020-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='path',
            field=models.FilePathField(max_length=200, path='/home/clari/media', recursive=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phasedataset',
            name='path',
            field=models.FilePathField(max_length=200, path='/home/clari/media', recursive=True),
        ),
    ]
